version: '3'
services:
  users:
    build:
      context: ./app/services/users
      dockerfile: Dockerfile
    env_file:
      - docker/dev/dev.env

    volumes:
      - './app/services:/app'
    ports:
      - '5000:5000'
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    ports:
      - '5431:5432'

  nginx:
    container_name: development_nginx
    build:
      context: ./app/services/nginx
      dockerfile: Dockerfile
    # volumes:
    #   - ./nginx:/etc/nginx/
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - '80:80'
