version: 2.0
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01

    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            docker-compose up -d --build
            docker-compose exec users pytest

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
# version: 2.0
# jobs:
#   build:
#     machine:
#       image: ubuntu-1604:201903-01
#     steps:
#       - checkout
#       - restore_cache:
#           key: deps1-{{ .Branch }}-{{ checksum "app/services/users/requirements.txt" }}
#       - run:
#           name: Install python peps in a venv
#           command: |
#             python -m virtualenv venv
#             . venv/bin/activate
#             pip install -r app/services/users/requirements.txt
#       - save_cache:
#           key: deps1-{{ .Branch }}-{{ checksum "app/services/users/requirements/dev.txt" }}
#           paths:
#             - 'venv'
#       - run:
#           name: unit tests
#           command: docker-compose exec users bash
# version: 2
# jobs:
#   build:
#     docker:
#       - image: python3.6

#     steps:
#       - checkout
#       - run:
#           name: Install python peps in a venv
#           command: |
#             python3 -m venv venv
#             . venv/bin/activate
#             pip install -r app/services/users/requirements.txt
#       - run:
#           name: run tests
#           command: |
#             - . venv/bin/activate
#             - pytest app/services/users/tests

# workflows:

