"""empty message

Revision ID: e2958707ecf4
Revises: 
Create Date: 2019-09-04 15:50:42.747321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2958707ecf4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_password_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_password_key', 'users', ['password'])
    # ### end Alembic commands ###
